/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-05-29 07:16:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import car.bean.UserSignUp;
import car.bean.UserSignUp;

public final class changepassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1716445596976L));
    _jspx_dependants.put("/owner-header.jsp", Long.valueOf(1716965818588L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1716965986503L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("car.bean.UserSignUp");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write(" ");

 
 	UserSignUp u1=null;
 	if(session != null)
 	{
 		u1=(UserSignUp)session.getAttribute("u");
 	}
 	
 	if(u1.getUsertype().equals("Owner"))
 	{

      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		UserSignUp u=null;
		if(session != null)
		{
			if(session.getAttribute("u") != null)
			{
				u=(UserSignUp)session.getAttribute("u");
			}
		}
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>ROYAL CARS - Car Rental HTML Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <div class=\"container-fluid position-relative nav-bar p-0\">\r\n");
      out.write("        <div class=\"position-relative px-lg-5\" style=\"z-index: 9;\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg bg-secondary navbar-dark py-3 py-lg-0 pl-3 pl-lg-5\">\r\n");
      out.write("                <a href=\"\" class=\"navbar-brand\">\r\n");
      out.write("                    <h1 class=\"text-uppercase text-primary mb-1\">Royal Cars</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse justify-content-between px-3\" id=\"navbarCollapse\">\r\n");
      out.write("                    <div class=\"navbar-nav ml-auto py-0\">\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write(" \r\n");
      out.write(" <!-- <a href=\"about.jsp\" class=\"nav-item nav-link\">About</a> -->\r\n");
      out.write(" <!-- <a href=\"service.jsp\" class=\"nav-item nav-link\">Service</a> -->\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Cars</a>\r\n");
      out.write("                            <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("                                <a href=\"car.jsp\" class=\"dropdown-item\">Car Listing</a>\r\n");
      out.write("                                <a href=\"detail.jsp\" class=\"dropdown-item\">Car Detail</a>\r\n");
      out.write("                                <a href=\"booking.jsp\" class=\"dropdown-item\">Car Booking</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                       <!--  <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Pages</a>\r\n");
      out.write("                            <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("                                <a href=\"team.jsp\" class=\"dropdown-item\">The Team</a>\r\n");
      out.write("                                <a href=\"testimonial.jsp\" class=\"dropdown-item\">Testimonial</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("        \r\n");
      out.write("        ");

	    
		    if(u == null)
		    {
	    
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("				<a href=\"signup.jsp\" class=\"nav-item nav-link\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a>\r\n");
      out.write("				<a href=\"login.jsp\" class=\"nav-item nav-link\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a>\r\n");
      out.write("	    \r\n");
      out.write("	    ");

	    
	    	}else{
	    
	    
      out.write("\r\n");
      out.write("	    	<div class=\"nav-item dropdown\">\r\n");
      out.write("	    	\r\n");
      out.write("	    		<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Profile</a>\r\n");
      out.write("	    		\r\n");
      out.write("                <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("	    			<a href=\"changepassword.jsp\" class=\"dropdown-item\"><span class=\"glyphicon glyphicon-edit\"></span> Change Password</a>\r\n");
      out.write("	    			<a href=\"logout.jsp\" class=\"dropdown-item\"><span class=\"glyphicon glyphicon-log-out\"></span> Logout(");
      out.print(u.getFname() );
      out.write(")</a>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    ");

	    	}
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');

 	}
 	else
 	{

      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		UserSignUp u=null;
		if(session != null)
		{
			if(session.getAttribute("u") != null)
			{
				u=(UserSignUp)session.getAttribute("u");
			}
		}
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>ROYAL CARS - Car Rental HTML Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark py-3 px-lg-5 d-none d-lg-block\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 text-center text-lg-left mb-2 mb-lg-0\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a class=\"text-body pr-3\" href=\"\"><i class=\"fa fa-phone-alt mr-2\"></i>+012 345 6789</a>\r\n");
      out.write("                    <span class=\"text-body\">|</span>\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\"><i class=\"fa fa-envelope mr-2\"></i>info@example.com</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 text-center text-lg-right\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-body pl-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <div class=\"container-fluid position-relative nav-bar p-0\">\r\n");
      out.write("        <div class=\"position-relative px-lg-5\" style=\"z-index: 9;\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg bg-secondary navbar-dark py-3 py-lg-0 pl-3 pl-lg-5\">\r\n");
      out.write("                <a href=\"\" class=\"navbar-brand\">\r\n");
      out.write("                    <h1 class=\"text-uppercase text-primary mb-1\">Royal Cars</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse justify-content-between px-3\" id=\"navbarCollapse\">\r\n");
      out.write("                    <div class=\"navbar-nav ml-auto py-0\">\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                        <a href=\"about.jsp\" class=\"nav-item nav-link\">About</a>\r\n");
      out.write("                        <a href=\"service.jsp\" class=\"nav-item nav-link\">Service</a>\r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Cars</a>\r\n");
      out.write("                            <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("                                <a href=\"car.jsp\" class=\"dropdown-item\">Car Listing</a>\r\n");
      out.write("                                <a href=\"detail.jsp\" class=\"dropdown-item\">Car Detail</a>\r\n");
      out.write("                                <a href=\"booking.jsp\" class=\"dropdown-item\">Car Booking</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("<!-- <div class=\"nav-item dropdown\">\r\n");
      out.write("    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Pages</a>\r\n");
      out.write("    <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("        <a href=\"team.jsp\" class=\"dropdown-item\">The Team</a>\r\n");
      out.write("        <a href=\"testimonial.jsp\" class=\"dropdown-item\">Testimonial</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div> -->\r\n");
      out.write("        \r\n");
      out.write("        ");

	    
		    if(u == null)
		    {
	    
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("				<a href=\"signup.jsp\" class=\"nav-item nav-link\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a>\r\n");
      out.write("				<a href=\"login.jsp\" class=\"nav-item nav-link\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a>\r\n");
      out.write("	    \r\n");
      out.write("	    ");

	    
	    	}else{
	    
	    
      out.write("\r\n");
      out.write("	    	<div class=\"nav-item dropdown\">\r\n");
      out.write("	    	\r\n");
      out.write("	    		<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Profile</a>\r\n");
      out.write("	    		\r\n");
      out.write("                <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("	    			<a href=\"changepassword.jsp\" class=\"dropdown-item\"><span class=\"glyphicon glyphicon-edit\"></span> Change Password</a>\r\n");
      out.write("	    			<a href=\"logout.jsp\" class=\"dropdown-item\"><span class=\"glyphicon glyphicon-log-out\"></span> Logout(");
      out.print(u.getFname() );
      out.write(")</a>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    ");

	    
	    	}
	    
	    
      out.write(" \r\n");
      out.write("	    \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Search Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-white pt-3 px-lg-5\">\r\n");
      out.write("        <div class=\"row mx-n2\">\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <select class=\"custom-select px-4 mb-3\" style=\"height: 50px;\">\r\n");
      out.write("                    <option selected>Pickup Location</option>\r\n");
      out.write("                    <option value=\"1\">Location 1</option>\r\n");
      out.write("                    <option value=\"2\">Location 2</option>\r\n");
      out.write("                    <option value=\"3\">Location 3</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <select class=\"custom-select px-4 mb-3\" style=\"height: 50px;\">\r\n");
      out.write("                    <option selected>Drop Location</option>\r\n");
      out.write("                    <option value=\"1\">Location 1</option>\r\n");
      out.write("                    <option value=\"2\">Location 2</option>\r\n");
      out.write("                    <option value=\"3\">Location 3</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <div class=\"date mb-3\" id=\"date\" data-target-input=\"nearest\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control p-4 datetimepicker-input\" placeholder=\"Pickup Date\"\r\n");
      out.write("                        data-target=\"#date\" data-toggle=\"datetimepicker\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <div class=\"time mb-3\" id=\"time\" data-target-input=\"nearest\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control p-4 datetimepicker-input\" placeholder=\"Pickup Time\"\r\n");
      out.write("                        data-target=\"#time\" data-toggle=\"datetimepicker\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <select class=\"custom-select px-4 mb-3\" style=\"height: 50px;\">\r\n");
      out.write("                    <option selected>Select A Car</option>\r\n");
      out.write("                    <option value=\"1\">Car 1</option>\r\n");
      out.write("                    <option value=\"2\">Car 1</option>\r\n");
      out.write("                    <option value=\"3\">Car 1</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <button class=\"btn btn-primary btn-block mb-3\" type=\"submit\" style=\"height: 50px;\">Search</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Search End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');

 	}
 
 
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>ROYAL CARS - Car Rental HTML Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Header Start -->\r\n");
      out.write("    <div class=\"container-fluid page-header\">\r\n");
      out.write("        <h1 class=\"display-3 text-uppercase text-white mb-3\">Change Password</h1>\r\n");
      out.write("        <div class=\"d-inline-flex text-white\">\r\n");
      out.write("            <h6 class=\"text-uppercase m-0\"><a class=\"text-white\" href=\"index.jsp\">Home</a></h6>\r\n");
      out.write("            <h6 class=\"text-body m-0 px-3\">/</h6>\r\n");
      out.write("            <h6 class=\"text-uppercase text-body m-0\">Change Password</h6>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Page Header End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Contact Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container pt-5 pb-3\">\r\n");
      out.write("            <h1 class=\"display-4 text-uppercase text-center mb-5\">Change Password</h1>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("            \r\n");
      out.write("            ");

				if(request.getAttribute("msg") != null){
			
      out.write("\r\n");
      out.write("				<h3> ");
      out.print(request.getAttribute("msg") );
      out.write(" </h3>\r\n");
      out.write("			");
		
				}
			
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"col-lg-7 mb-2\">\r\n");
      out.write("                    <div class=\"contact-form bg-light mb-4\" style=\"padding: 30px;\">\r\n");
      out.write("                        <form name=\"frm\" method=\"post\" action=\"UserSignUpController\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                               \r\n");
      out.write("                                <div class=\"col-6 form-group\">\r\n");
      out.write("                                    <input type=\"password\" class=\"form-control p-4\" placeholder=\"Your Old Password\" required=\"required\" name=\"oldpassword\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"col-6 form-group\">\r\n");
      out.write("                                    <input type=\"password\" class=\"form-control p-4\" placeholder=\"Your New Password\" required=\"required\" name=\"newpassword\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"col-6 form-group\">\r\n");
      out.write("                                    <input type=\"password\" class=\"form-control p-4\" placeholder=\"Your Confirm New Password\" required=\"required\" name=\"cpassword\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <button class=\"btn btn-primary py-3 px-5\" type=\"submit\" value=\"changepassword\" name=\"action\">Change Password</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Contact End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendor Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"owl-carousel vendor-carousel\">\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-1.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-2.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-3.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-4.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-5.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-6.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-7.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-8.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Vendor End -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>ROYAL CARS - Car Rental HTML Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary py-5 px-sm-3 px-md-5\" style=\"margin-top: 90px;\">\r\n");
      out.write("        <div class=\"row pt-5\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 mb-5\">\r\n");
      out.write("                <h4 class=\"text-uppercase text-light mb-4\">Get In Touch</h4>\r\n");
      out.write("                <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt text-white mr-3\"></i>123 Street, New York, USA</p>\r\n");
      out.write("                <p class=\"mb-2\"><i class=\"fa fa-phone-alt text-white mr-3\"></i>+012 345 67890</p>\r\n");
      out.write("                <p><i class=\"fa fa-envelope text-white mr-3\"></i>info@example.com</p>\r\n");
      out.write("                <h6 class=\"text-uppercase text-white py-2\">Follow Us</h6>\r\n");
      out.write("                <div class=\"d-flex justify-content-start\">\r\n");
      out.write("                    <a class=\"btn btn-lg btn-dark btn-lg-square mr-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-lg btn-dark btn-lg-square mr-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-lg btn-dark btn-lg-square mr-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-lg btn-dark btn-lg-square\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 mb-5\">\r\n");
      out.write("                <h4 class=\"text-uppercase text-light mb-4\">Usefull Links</h4>\r\n");
      out.write("                <div class=\"d-flex flex-column justify-content-start\">\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Private Policy</a>\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Term & Conditions</a>\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>New Member Registration</a>\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Affiliate Programme</a>\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Return & Refund</a>\r\n");
      out.write("                    <a class=\"text-body\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Help & FQAs</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 mb-5\">\r\n");
      out.write("                <h4 class=\"text-uppercase text-light mb-4\">Car Gallery</h4>\r\n");
      out.write("                <div class=\"row mx-n1\">\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-1.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-2.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-3.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-4.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-5.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-6.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 mb-5\">\r\n");
      out.write("                <h4 class=\"text-uppercase text-light mb-4\">Newsletter</h4>\r\n");
      out.write("                <p class=\"mb-4\">Volup amet magna clita tempor. Tempor sea eos vero ipsum. Lorem lorem sit sed elitr sed kasd et</p>\r\n");
      out.write("                <div class=\"w-100 mb-3\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control bg-dark border-dark\" style=\"padding: 25px;\" placeholder=\"Your Email\">\r\n");
      out.write("                        <div class=\"input-group-append\">\r\n");
      out.write("                            <button class=\"btn btn-primary text-uppercase px-3\">Sign Up</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <i>Lorem sit sed elitr sed kasd et</i>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container-fluid bg-dark py-4 px-sm-3 px-md-5\">\r\n");
      out.write("        <p class=\"mb-2 text-center text-body\">&copy; <a href=\"#\">Your Site Name</a>. All Rights Reserved.</p>\r\n");
      out.write("        <p class=\"m-0 text-center text-body\">Designed by <a href=\"https://htmlcodex.com\">HTML Codex</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top\"><i class=\"fa fa-angle-double-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
