/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-06-03 11:41:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import car.bean.UserSignUp;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("car.bean.UserSignUp");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		UserSignUp u=null;
		if(session != null)
		{
			if(session.getAttribute("u") != null)
			{
				u=(UserSignUp)session.getAttribute("u");
			}
		}
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>ROYAL CARS - Car Rental HTML Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark py-3 px-lg-5 d-none d-lg-block\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 text-center text-lg-left mb-2 mb-lg-0\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a class=\"text-body pr-3\" href=\"\"><i class=\"fa fa-phone-alt mr-2\"></i>+012 345 6789</a>\r\n");
      out.write("                    <span class=\"text-body\">|</span>\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\"><i class=\"fa fa-envelope mr-2\"></i>info@example.com</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 text-center text-lg-right\">\r\n");
      out.write("                <div class=\"d-inline-flex align-items-center\">\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-body px-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a class=\"text-body pl-3\" href=\"\">\r\n");
      out.write("                        <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <div class=\"container-fluid position-relative nav-bar p-0\">\r\n");
      out.write("        <div class=\"position-relative px-lg-5\" style=\"z-index: 9;\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg bg-secondary navbar-dark py-3 py-lg-0 pl-3 pl-lg-5\">\r\n");
      out.write("                <a href=\"\" class=\"navbar-brand\">\r\n");
      out.write("                    <h1 class=\"text-uppercase text-primary mb-1\">Royal Cars</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse justify-content-between px-3\" id=\"navbarCollapse\">\r\n");
      out.write("                    <div class=\"navbar-nav ml-auto py-0\">\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                        <a href=\"about.jsp\" class=\"nav-item nav-link\">About</a>\r\n");
      out.write("                        <a href=\"service.jsp\" class=\"nav-item nav-link\">Service</a>\r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Cars</a>\r\n");
      out.write("                            <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("                                <a href=\"car.jsp\" class=\"dropdown-item\">All Cars</a>\r\n");
      out.write("                                <a href=\"detail.jsp\" class=\"dropdown-item\">Car Detail</a>\r\n");
      out.write("                                <a href=\"car-single.jsp\" class=\"dropdown-item\">Car Booking</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("<!-- <div class=\"nav-item dropdown\">\r\n");
      out.write("    <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Pages</a>\r\n");
      out.write("    <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("        <a href=\"team.jsp\" class=\"dropdown-item\">The Team</a>\r\n");
      out.write("        <a href=\"testimonial.jsp\" class=\"dropdown-item\">Testimonial</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div> -->\r\n");
      out.write("        \r\n");
      out.write("        ");

	    
		    if(u == null)
		    {
	    
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("				<a href=\"signup.jsp\" class=\"nav-item nav-link\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a>\r\n");
      out.write("				<a href=\"login.jsp\" class=\"nav-item nav-link\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a>\r\n");
      out.write("	    \r\n");
      out.write("	    ");

	    
	    	}else{
	    
	    
      out.write("\r\n");
      out.write("	    	<div class=\"nav-item dropdown\">\r\n");
      out.write("	    	\r\n");
      out.write("	    		<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Profile</a>\r\n");
      out.write("	    		\r\n");
      out.write("                <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("	    			<a href=\"changepassword.jsp\" class=\"dropdown-item\"><span class=\"glyphicon glyphicon-edit\"></span> Change Password</a>\r\n");
      out.write("	    			<a href=\"logout.jsp\" class=\"dropdown-item\"><span class=\"glyphicon glyphicon-log-out\"></span> Logout(");
      out.print(u.getFname() );
      out.write(")</a>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    ");

	    
	    	}
	    
	    
      out.write(" \r\n");
      out.write("	    \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Search Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-white pt-3 px-lg-5\">\r\n");
      out.write("        <div class=\"row mx-n2\">\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <select class=\"custom-select px-4 mb-3\" style=\"height: 50px;\">\r\n");
      out.write("                    <option selected>Pickup Location</option>\r\n");
      out.write("                    <option value=\"1\">Location 1</option>\r\n");
      out.write("                    <option value=\"2\">Location 2</option>\r\n");
      out.write("                    <option value=\"3\">Location 3</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <select class=\"custom-select px-4 mb-3\" style=\"height: 50px;\">\r\n");
      out.write("                    <option selected>Drop Location</option>\r\n");
      out.write("                    <option value=\"1\">Location 1</option>\r\n");
      out.write("                    <option value=\"2\">Location 2</option>\r\n");
      out.write("                    <option value=\"3\">Location 3</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <div class=\"date mb-3\" id=\"date\" data-target-input=\"nearest\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control p-4 datetimepicker-input\" placeholder=\"Pickup Date\"\r\n");
      out.write("                        data-target=\"#date\" data-toggle=\"datetimepicker\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <div class=\"time mb-3\" id=\"time\" data-target-input=\"nearest\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control p-4 datetimepicker-input\" placeholder=\"Pickup Time\"\r\n");
      out.write("                        data-target=\"#time\" data-toggle=\"datetimepicker\" />\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <select class=\"custom-select px-4 mb-3\" style=\"height: 50px;\">\r\n");
      out.write("                    <option selected>Select A Car</option>\r\n");
      out.write("                    <option value=\"1\">Car 1</option>\r\n");
      out.write("                    <option value=\"2\">Car 1</option>\r\n");
      out.write("                    <option value=\"3\">Car 1</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xl-2 col-lg-4 col-md-6 px-2\">\r\n");
      out.write("                <button class=\"btn btn-primary btn-block mb-3\" type=\"submit\" style=\"height: 50px;\">Search</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Search End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
