/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-06-04 12:00:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import car.dao.CarDao;
import car.bean.Car;
import java.util.List;
import car.bean.UserSignUp;

public final class owner_002dindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1717389219392L));
    _jspx_dependants.put("/owner-header.jsp", Long.valueOf(1717502222378L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("car.bean.UserSignUp");
    _jspx_imports_classes.add("car.dao.CarDao");
    _jspx_imports_classes.add("car.bean.Car");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		UserSignUp u=null;
		if(session != null)
		{
			if(session.getAttribute("u") != null)
			{
				u=(UserSignUp)session.getAttribute("u");
			}
		}
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>ROYAL CARS - Car Rental HTML Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <div class=\"container-fluid position-relative nav-bar p-0\">\r\n");
      out.write("        <div class=\"position-relative px-lg-5\" style=\"z-index: 9;\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg bg-secondary navbar-dark py-3 py-lg-0 pl-3 pl-lg-5\">\r\n");
      out.write("                <a href=\"\" class=\"navbar-brand\">\r\n");
      out.write("                    <h1 class=\"text-uppercase text-primary mb-1\">Royal Cars</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse justify-content-between px-3\" id=\"navbarCollapse\">\r\n");
      out.write("                    <div class=\"navbar-nav ml-auto py-0\">\r\n");
      out.write("                        <a href=\"index.jsp\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Cars</a>\r\n");
      out.write("                            <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("                                <a href=\"add-car.jsp\" class=\"dropdown-item\">Add Car</a>\r\n");
      out.write("                                <a href=\"view-car.jsp\" class=\"dropdown-item\">View Car</a>\r\n");
      out.write("                                <a href=\"booking.jsp\" class=\"dropdown-item\">Car Booking</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                       <!--  <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Pages</a>\r\n");
      out.write("                            <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("                                <a href=\"team.jsp\" class=\"dropdown-item\">The Team</a>\r\n");
      out.write("                                <a href=\"testimonial.jsp\" class=\"dropdown-item\">Testimonial</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> -->\r\n");
      out.write("        \r\n");
      out.write("        ");

	    
		    if(u == null)
		    {
	    
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("				<a href=\"signup.jsp\" class=\"nav-item nav-link\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a>\r\n");
      out.write("				<a href=\"login.jsp\" class=\"nav-item nav-link\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a>\r\n");
      out.write("	    \r\n");
      out.write("	    ");

	    
	    	}else{
	    
	    
      out.write("\r\n");
      out.write("	    	<div class=\"nav-item dropdown\">\r\n");
      out.write("	    	\r\n");
      out.write("	    		<a href=\"#\" class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\">Profile</a>\r\n");
      out.write("	    		\r\n");
      out.write("                <div class=\"dropdown-menu rounded-0 m-0\">\r\n");
      out.write("	    			<a href=\"changepassword.jsp\" class=\"dropdown-item\"><span class=\"glyphicon glyphicon-edit\"></span> Change Password</a>\r\n");
      out.write("	    			<a href=\"logout.jsp\" class=\"dropdown-item\"><span class=\"glyphicon glyphicon-log-out\"></span> Logout(");
      out.print(u.getFname() );
      out.write(")</a>\r\n");
      out.write("	    		</div>\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    ");

	    	}
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>ROYAL CARS - Car Rental HTML Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("	<link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Google Web Fonts -->\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("	<link\r\n");
      out.write("		href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap\"\r\n");
      out.write("		rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Font Awesome -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\" integrity=\"sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("	\r\n");
      out.write("	<!-- Libraries Stylesheet -->\r\n");
      out.write("	<link href=\"lib/owlcarousel/assets/owl.carousel.min.css\"\r\n");
      out.write("		rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\"\r\n");
      out.write("		rel=\"stylesheet\" />\r\n");
      out.write("		\r\n");
      out.write("	<!-- Bootstrap CSS -->\r\n");
      out.write("	    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<!-- Bootstrap Icons CSS -->\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("	<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Template Stylesheet -->\r\n");
      out.write("	<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Carousel Start -->\r\n");
      out.write("    <div class=\"container-fluid p-0\" style=\"margin-bottom: 90px;\">\r\n");
      out.write("        <div id=\"header-carousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"img/carousel-1.jpg\" alt=\"Image\">\r\n");
      out.write("                    <div class=\"carousel-caption d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("                        <div class=\"p-3\" style=\"max-width: 900px;\">\r\n");
      out.write("                            <h4 class=\"text-white text-uppercase mb-md-3\">Rent A Car</h4>\r\n");
      out.write("                            <h1 class=\"display-1 text-white mb-md-4\">Best Rental Cars In Your Location</h1>\r\n");
      out.write("                            <a href=\"\" class=\"btn btn-primary py-md-3 px-md-5 mt-2\">Reserve Now</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"img/carousel-2.jpg\" alt=\"Image\">\r\n");
      out.write("                    <div class=\"carousel-caption d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("                        <div class=\"p-3\" style=\"max-width: 900px;\">\r\n");
      out.write("                            <h4 class=\"text-white text-uppercase mb-md-3\">Rent A Car</h4>\r\n");
      out.write("                            <h1 class=\"display-1 text-white mb-md-4\">Quality Cars with Unlimited Miles</h1>\r\n");
      out.write("                            <a href=\"\" class=\"btn btn-primary py-md-3 px-md-5 mt-2\">Reserve Now</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"carousel-control-prev\" href=\"#header-carousel\" data-slide=\"prev\">\r\n");
      out.write("                <div class=\"btn btn-dark\" style=\"width: 45px; height: 45px;\">\r\n");
      out.write("                    <span class=\"carousel-control-prev-icon mb-n2\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"carousel-control-next\" href=\"#header-carousel\" data-slide=\"next\">\r\n");
      out.write("                <div class=\"btn btn-dark\" style=\"width: 45px; height: 45px;\">\r\n");
      out.write("                    <span class=\"carousel-control-next-icon mb-n2\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Carousel End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- About Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container pt-5 pb-3\">\r\n");
      out.write("            <h1 class=\"display-4 text-uppercase text-center mb-5\">Welcome To <span class=\"text-primary\">Royal Cars</span></h1>\r\n");
      out.write("            <div class=\"row justify-content-center\">\r\n");
      out.write("                <div class=\"col-lg-10 text-center\">\r\n");
      out.write("                    <img class=\"w-75 mb-4\" src=\"img/about.png\" alt=\"\">\r\n");
      out.write("                    <p>Justo et eos et ut takimata sed sadipscing dolore lorem, et elitr labore labore voluptua no rebum sed, stet voluptua amet sed elitr ea dolor dolores no clita. Dolores diam magna clita ea eos amet, amet rebum voluptua vero vero sed clita accusam takimata. Nonumy labore ipsum sea voluptua sea eos sit justo, no ipsum sanctus sanctus no et no ipsum amet, tempor labore est labore no. Eos diam eirmod lorem ut eirmod, ipsum diam sadipscing stet dolores elitr elitr eirmod dolore. Magna elitr accusam takimata labore, et at erat eirmod consetetur tempor eirmod invidunt est, ipsum nonumy at et.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row mt-3\">\r\n");
      out.write("                <div class=\"col-lg-4 mb-2\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center bg-light p-4 mb-4\" style=\"height: 150px;\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4\" style=\"width: 100px; height: 100px;\">\r\n");
      out.write("                            <i class=\"fa fa-2x fa-headset text-secondary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-uppercase m-0\">24/7 Car Rental Support</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 mb-2\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center bg-secondary p-4 mb-4\" style=\"height: 150px;\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4\" style=\"width: 100px; height: 100px;\">\r\n");
      out.write("                            <i class=\"fa fa-2x fa-car text-secondary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-light text-uppercase m-0\">Car Reservation Anytime</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 mb-2\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center bg-light p-4 mb-4\" style=\"height: 150px;\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-center flex-shrink-0 bg-primary ml-n4 mr-4\" style=\"width: 100px; height: 100px;\">\r\n");
      out.write("                            <i class=\"fa fa-2x fa-map-marker-alt text-secondary\"></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-uppercase m-0\">Lots Of Pickup Locations</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- About End -->\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Services Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container pt-5 pb-3\">\r\n");
      out.write("            <h1 class=\"display-4 text-uppercase text-center mb-5\">Our Services</h1>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-2\">\r\n");
      out.write("                    <div class=\"service-item d-flex flex-column justify-content-center px-4 mb-4\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-center bg-primary ml-n4\" style=\"width: 80px; height: 80px;\">\r\n");
      out.write("                                <i class=\"fa fa-2x fa-taxi text-secondary\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"display-2 text-white mt-n2 m-0\">01</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-3\">Car Rental</h4>\r\n");
      out.write("                        <p class=\"m-0\">Kasd dolor no lorem nonumy sit labore tempor at justo rebum rebum stet, justo elitr dolor amet sit sea sed</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-2\">\r\n");
      out.write("                    <div class=\"service-item active d-flex flex-column justify-content-center px-4 mb-4\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-center bg-primary ml-n4\" style=\"width: 80px; height: 80px;\">\r\n");
      out.write("                                <i class=\"fa fa-2x fa-money-check-alt text-secondary\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"display-2 text-white mt-n2 m-0\">02</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-3\">Car Financing</h4>\r\n");
      out.write("                        <p class=\"m-0\">Kasd dolor no lorem nonumy sit labore tempor at justo rebum rebum stet, justo elitr dolor amet sit sea sed</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-2\">\r\n");
      out.write("                    <div class=\"service-item d-flex flex-column justify-content-center px-4 mb-4\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-center bg-primary ml-n4\" style=\"width: 80px; height: 80px;\">\r\n");
      out.write("                                <i class=\"fa fa-2x fa-car text-secondary\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"display-2 text-white mt-n2 m-0\">03</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-3\">Car Inspection</h4>\r\n");
      out.write("                        <p class=\"m-0\">Kasd dolor no lorem nonumy sit labore tempor at justo rebum rebum stet, justo elitr dolor amet sit sea sed</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-2\">\r\n");
      out.write("                    <div class=\"service-item d-flex flex-column justify-content-center px-4 mb-4\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-center bg-primary ml-n4\" style=\"width: 80px; height: 80px;\">\r\n");
      out.write("                                <i class=\"fa fa-2x fa-cogs text-secondary\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"display-2 text-white mt-n2 m-0\">04</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-3\">Auto Repairing</h4>\r\n");
      out.write("                        <p class=\"m-0\">Kasd dolor no lorem nonumy sit labore tempor at justo rebum rebum stet, justo elitr dolor amet sit sea sed</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-2\">\r\n");
      out.write("                    <div class=\"service-item d-flex flex-column justify-content-center px-4 mb-4\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-center bg-primary ml-n4\" style=\"width: 80px; height: 80px;\">\r\n");
      out.write("                                <i class=\"fa fa-2x fa-spray-can text-secondary\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"display-2 text-white mt-n2 m-0\">05</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-3\">Auto Painting</h4>\r\n");
      out.write("                        <p class=\"m-0\">Kasd dolor no lorem nonumy sit labore tempor at justo rebum rebum stet, justo elitr dolor amet sit sea sed</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6 mb-2\">\r\n");
      out.write("                    <div class=\"service-item d-flex flex-column justify-content-center px-4 mb-4\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-between mb-3\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-center bg-primary ml-n4\" style=\"width: 80px; height: 80px;\">\r\n");
      out.write("                                <i class=\"fa fa-2x fa-pump-soap text-secondary\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h1 class=\"display-2 text-white mt-n2 m-0\">06</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-3\">Auto Cleaning</h4>\r\n");
      out.write("                        <p class=\"m-0\">Kasd dolor no lorem nonumy sit labore tempor at justo rebum rebum stet, justo elitr dolor amet sit sea sed</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Services End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Rent A Car Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container pt-5 pb-3\">\r\n");
      out.write("            <h1 class=\"display-4 text-uppercase text-center mb-5\">Find Your Car</h1>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("				");

					List<Car> list = CarDao.getAllCars();
					for (Car c : list) {
				
      out.write("\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6 mb-2\">\r\n");
      out.write("					<div class=\"rent-item mb-4\">\r\n");
      out.write("						<img class=\"img-fluid mb-4\"\r\n");
      out.write("							src=\"");
      out.print(request.getContextPath() + "/car_images/" + c.getCar_image());
      out.write("\"\r\n");
      out.write("							alt=\"");
      out.print(c.getCar_image());
      out.write("\">\r\n");
      out.write("						<h4 class=\"text-uppercase mb-4\">");
      out.print(c.getCar_name());
      out.write("</h4>\r\n");
      out.write("						<div class=\"d-flex justify-content-center mb-4\">\r\n");
      out.write("							<div class=\"px-2\">\r\n");
      out.write("								<i class=\"fa fa-car text-primary mr-1\"></i> <span>");
      out.print(c.getCar_fuel());
      out.write("</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"px-2 border-left border-right\">\r\n");
      out.write("								<i class=\"fa fa-cogs text-primary mr-1\"></i> <span>");
      out.print(c.getCar_transmission());
      out.write("</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"px-2 border-left border-right\">\r\n");
      out.write("								<i class=\"fa fa-road text-primary mr-1\"></i> <span>");
      out.print(c.getCar_mileage());
      out.write("\r\n");
      out.write("									Mileage</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"px-2\">\r\n");
      out.write("								<i class=\"fa fa-inr text-primary\"></i> <span>");
      out.print(c.getCar_ppd());
      out.write("/Day\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a class=\"btn btn-primary px-5\"\r\n");
      out.write("							href=\"car-single.jsp?cid=");
      out.print(c.getCid());
      out.write("\">Details</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	<!-- Rent A Car End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Banner Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row mx-0\">\r\n");
      out.write("                <div class=\"col-lg-6 px-0\">\r\n");
      out.write("                    <div class=\"px-5 bg-secondary d-flex align-items-center justify-content-between\" style=\"height: 350px;\">\r\n");
      out.write("                        <img class=\"img-fluid flex-shrink-0 ml-n5 w-50 mr-4\" src=\"img/banner-left.png\" alt=\"\">\r\n");
      out.write("                        <div class=\"text-right\">\r\n");
      out.write("                            <h3 class=\"text-uppercase text-light mb-3\">Want to be driver?</h3>\r\n");
      out.write("                            <p class=\"mb-4\">Lorem justo sit sit ipsum eos lorem kasd, kasd labore</p>\r\n");
      out.write("                            <a class=\"btn btn-primary py-2 px-4\" href=\"\">Start Now</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-6 px-0\">\r\n");
      out.write("                    <div class=\"px-5 bg-dark d-flex align-items-center justify-content-between\" style=\"height: 350px;\">\r\n");
      out.write("                        <div class=\"text-left\">\r\n");
      out.write("                            <h3 class=\"text-uppercase text-light mb-3\">Looking for a car?</h3>\r\n");
      out.write("                            <p class=\"mb-4\">Lorem justo sit sit ipsum eos lorem kasd, kasd labore</p>\r\n");
      out.write("                            <a class=\"btn btn-primary py-2 px-4\" href=\"\">Start Now</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <img class=\"img-fluid flex-shrink-0 mr-n5 w-50 ml-4\" src=\"img/banner-right.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Banner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendor Start -->\r\n");
      out.write("    <div class=\"container-fluid py-5\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"owl-carousel vendor-carousel\">\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-1.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-2.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-3.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-4.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-5.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-6.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-7.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"bg-light p-4\">\r\n");
      out.write("                    <img src=\"img/vendor-8.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Vendor End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>ROYAL CARS - Car Rental HTML Template</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Rubik&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary py-5 px-sm-3 px-md-5\" style=\"margin-top: 90px;\">\r\n");
      out.write("        <div class=\"row pt-5\">\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 mb-5\">\r\n");
      out.write("                <h4 class=\"text-uppercase text-light mb-4\">Get In Touch</h4>\r\n");
      out.write("                <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt text-white mr-3\"></i>123 Street, New York, USA</p>\r\n");
      out.write("                <p class=\"mb-2\"><i class=\"fa fa-phone-alt text-white mr-3\"></i>+012 345 67890</p>\r\n");
      out.write("                <p><i class=\"fa fa-envelope text-white mr-3\"></i>info@example.com</p>\r\n");
      out.write("                <h6 class=\"text-uppercase text-white py-2\">Follow Us</h6>\r\n");
      out.write("                <div class=\"d-flex justify-content-start\">\r\n");
      out.write("                    <a class=\"btn btn-lg btn-dark btn-lg-square mr-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-lg btn-dark btn-lg-square mr-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-lg btn-dark btn-lg-square mr-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    <a class=\"btn btn-lg btn-dark btn-lg-square\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 mb-5\">\r\n");
      out.write("                <h4 class=\"text-uppercase text-light mb-4\">Usefull Links</h4>\r\n");
      out.write("                <div class=\"d-flex flex-column justify-content-start\">\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Private Policy</a>\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Term & Conditions</a>\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>New Member Registration</a>\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Affiliate Programme</a>\r\n");
      out.write("                    <a class=\"text-body mb-2\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Return & Refund</a>\r\n");
      out.write("                    <a class=\"text-body\" href=\"#\"><i class=\"fa fa-angle-right text-white mr-2\"></i>Help & FQAs</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 mb-5\">\r\n");
      out.write("                <h4 class=\"text-uppercase text-light mb-4\">Car Gallery</h4>\r\n");
      out.write("                <div class=\"row mx-n1\">\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-1.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-2.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-3.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-4.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-5.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4 px-1 mb-2\">\r\n");
      out.write("                        <a href=\"\"><img class=\"w-100\" src=\"img/gallery-6.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-3 col-md-6 mb-5\">\r\n");
      out.write("                <h4 class=\"text-uppercase text-light mb-4\">Newsletter</h4>\r\n");
      out.write("                <p class=\"mb-4\">Volup amet magna clita tempor. Tempor sea eos vero ipsum. Lorem lorem sit sed elitr sed kasd et</p>\r\n");
      out.write("                <div class=\"w-100 mb-3\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control bg-dark border-dark\" style=\"padding: 25px;\" placeholder=\"Your Email\">\r\n");
      out.write("                        <div class=\"input-group-append\">\r\n");
      out.write("                            <button class=\"btn btn-primary text-uppercase px-3\">Sign Up</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <i>Lorem sit sed elitr sed kasd et</i>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container-fluid bg-dark py-4 px-sm-3 px-md-5\">\r\n");
      out.write("        <p class=\"mb-2 text-center text-body\">&copy; <a href=\"#\">Your Site Name</a>. All Rights Reserved.</p>\r\n");
      out.write("        <p class=\"m-0 text-center text-body\">Designed by <a href=\"https://htmlcodex.com\">HTML Codex</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top\"><i class=\"fa fa-angle-double-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
